# Generated by Django 2.2.16 on 2022-05-21 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_auto_20220521_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='in_favorites',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='in_shopping_card',
            field=models.ManyToManyField(related_name='shopping_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
